### ISSUE TITLE
Optimized Response Generation

### ISSUE THREAD

**Issue by rahmansahinler1** [rahmansahinler1/ragchat_local#12]
**Description**
Increased context sized with upper and lower sentence. Also, increased prompting capabilities.

**Workflow**
1- Add a logic for taking upper and lower sentences then put them in the given context
2- Research advanced prompting techniques
3- Implement prompting algorithm

**Acceptance Criteria**
Optimized responses if there is. If there is no meaningful context given model should inform  the user.

**Comment by ozgurnsahin** [comment]
Added upper and lower sentences of most relevant sentences to the context
Created prompt templates to give instructions to the chat model and implemented prompt engineering algorithms
