### ISSUE TITLE
Good and Bad Questions

### ISSUE THREAD

**Issue by ozgurnsahin** [rahmansahinler1/ragchat_local#33]
**Description**
Its observed that answer quality depends on the question structure, if we can control the user question and put it into pre-defined structures it can increase answer quality.

**Workflow**
1-Determine the question type (general or detailed).
2-Determine good question structure based on type.
3-Extract fundamental parts of the question.
4-Create a logic to put user question into the classified structure.

**Acceptance Criteria**
%50 Improvement on question score that are effected by this feature (F2).

**Comment by Obgoktas** [comment]
It has been found that changing query structure does not increase the accuracy considerably.
