### ISSUE TITLE
Unstructured Information Extraction

### ISSUE THREAD

**Issue by ozgurnsahin** [rahmansahinler1/ragchat_local#37]
Description
Ragchat cant handle unstructured sentences format like tables, formulas, number etc.

Workflow
1-Implement a function to extract unstructured information.

Acceptance Criteria
Extract unstructured information.

**Comment by ozgurnsahin** [comment]
Upadate:

Trying to use fitz build-in 'page.find_tables()' function to detect tables page by page  and get the bbox(table coordinates) of the table with this info we can get the bbox text by 'get_text(clip = bbox)' but this function cant be generalized needs fine tuning or implementing a hand created function to detect the tables.

**Comment by ozgurnsahin** [comment]
Update:

Built-in find_tables() can find correctly structured tables. An initial function is intagrated but iy needs to be expanded on.

Development points:
1-Function needs to detect less structured tables.
2-Determine the table extract storage method and type.
3-While getting the extract we need to by pass page's text interaction thus ensure info is not extracted twice.

**Comment by rahmansahinler1** [comment]
Can we retrieve table information with using additional llm?
https://www.youtube.com/watch?v=Fb-6K00SUtc
https://huggingface.co/google/tapas-base-finetuned-wtq

**Comment by ozgurnsahin** [comment]
Workflow:
1-Detection:
- Research and implement a model based table detection logic to find structured or unstructured tables.
2-Extraction:
- Extract the table as a whole and keep its meaning and details intact to properly embed the table data.(Here create an new dictionary key)
3-Embeddings:
- Embed tabular extracted data.
 (Here we can use additional embedding models to embed these tabular data to ensure data is keeping its meaning as a whole with this addition we need to test if different embedding models faiss indexes still works and give meaningful distances.)
4-Intagrate tabular search:
- Add the tabular index search to generate response flow. (First search query on headers than in tabular data embeddings than on sentences here we need to also test if query and information embeddings model must be the same ? does it differ when models are different ?)
5-QA:
- Ask question to these tabular data and give referances from tabular data as a whole tabular format.

**Comment by ozgurnsahin** [comment]
Table extraction logic is implemented fully with using pymupdf find_tables logic.

![Image](https://github.com/user-attachments/assets/c1aaaafe-b554-439d-b7a3-e3c6459351a7)
