### ISSUE TITLE
File Header Search

### ISSUE THREAD

**Issue by ozgurnsahin** [rahmansahinler1/ragchat_local#43]
Description
To improve extracting capability we will implement searching by document file header (first page context header of the file).

Workflow
1-Implement a logic toget files first page header.
2-Attach this header data to file metadata.
3-Create search logic to look through file headers.
4-Update search output vector.
5-Test outcome with same conditions.

Acceptance Criteria
At least %10 improvement on the question scores that are effected by this feature.

**Comment by ozgurnsahin** [comment]
Integrated boosting within search:
1-Create a boosting np.array as long as sentences list to store all fo the senteces boost coefficient
2-Manipulate the boost coefficients of most similar file_header's file sentences
3-Multiply boost coefficients with all sentences distances
4-Sort senteces according to last boosted distances
5-Create context from top 10 sentences

**Comment by Obgoktas** [comment]
Reading function for file header extraction. Search with file headers logic implemented, dynamic boosting per file sentences. New query preprocessing function, query prompt changed.

**Improvements**
28 tests from 70 test.
191 total points --> 205 total points.
%7 Accuracy imrpovement.
