### ISSUE TITLE
Do not understand the query bug.

### ISSUE THREAD

**Issue by Obgoktas** [rahmansahinler1/ragchat_local#52]
Description
When I upload and ask a domain I always get, "I don't understand the query" answer.

![resim_2024-11-07_174526459](https://github.com/user-attachments/assets/f9952746-ea44-455a-938e-fa75fb27a8db)

**Comment by Obgoktas** [comment]
PDF (RAGLAB):
https://arxiv.org/pdf/2408.11381

**Comment by Obgoktas** [comment]
I uploaded only 1 document and it was showing 1 on the left panel but, when I delete it, deleted 2 docs??
![image](https://github.com/user-attachments/assets/bea5fffd-95b6-4290-955b-0959b07e08e7)

**Comment by rahmansahinler1** [comment]
![image](https://github.com/user-attachments/assets/0ee20b27-ffc6-494f-b39f-4ba6e75dbef1)

fixed. loop was the issue. table chunk did not referenced it was crushing the reference generation logic

**Comment by rahmansahinler1** [comment]
@Obgoktas next time use ragchat repo instead while openning issues
